[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin-contracts/contracts/=lib/openzeppelin-contracts/contracts/",
    "@v4-core/contracts/=lib/v4-core/contracts/",
    "@v4-periphery/contracts/=lib/v4-periphery/contracts/",
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
